apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-app-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/andresafag/app-manifests.git'
    targetRevision: main
    path: argocd-root/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: store-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




