frontend:
  replicaCount: 2
  image: 
    repository: andresafag/python-frontend
    tag: "a55fc4bbf1cd685391b598730ebe0510f8c95546"
    pullPolicy: Always
database:
  replicaCount: 1
  image: 
    repository: andresafag/postgres-db
    tag: "a55fc4bbf1cd685391b598730ebe0510f8c95546"
    pullPolicy: Always
  
