frontend:
  replicaCount: 2
  image: 
    repository: andresafag/python-frontend
    tag: "8280dcbfcd4580e3825f93c1b0554e246d84c731"
    pullPolicy: Always
database:
  replicaCount: 1
  image: 
    repository: andresafag/postgres-db
    tag: "8280dcbfcd4580e3825f93c1b0554e246d84c731"
    pullPolicy: Always
  
