apiVersion: v1
kind: Service
metadata:
  name: my-db
  namespace: default
  labels:
    app: my-db
spec:
  selector:
    app: my-db
  ports:
  - port: 5432
    targetPort: 5432
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: python-store-service
  namespace: default
  labels:
    app: python-store
spec:
  selector:
    app: python-store
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort